# Generated by Django 5.1.6 on 2025-06-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('Quaification', models.CharField(max_length=50)),
                ('where_are_you_from', models.CharField(max_length=50)),
            ],
        ),
    ]
