# Generated by Django 5.1.6 on 2025-06-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amora', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='Quaification',
            new_name='Qualification',
        ),
        migrations.AlterField(
            model_name='registration',
            name='mobile_number',
            field=models.CharField(max_length=15),
        ),
    ]
