# Generated by Django 5.1.6 on 2025-06-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amora', '0002_rename_quaification_registration_qualification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('desc', models.TextField()),
            ],
        ),
    ]
