# Generated by Django 5.1.6 on 2025-06-17 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Amora', '0003_modelname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModelName',
            new_name='Skilled_Jobs',
        ),
    ]
