# Generated by Django 5.1.6 on 2025-06-17 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Amora', '0005_unkilled_jobs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Unkilled_Jobs',
            new_name='Unskilled_Jobs',
        ),
    ]
