# Generated by Django 5.1.6 on 2025-06-20 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amora', '0006_rename_unkilled_jobs_unskilled_jobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
            ],
        ),
    ]
