# Generated by Django 5.1.6 on 2025-06-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amora', '0007_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='what_type_of_job',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
